//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USSR2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.CandidateExams = new HashSet<CandidateExam>();
        }
    
        public int CandidateID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PassportDetails { get; set; }
        public string ContactDetails { get; set; }
        public string Email { get; set; }
        public string INN { get; set; }
        public string SNILS { get; set; }
        public Nullable<double> CertificateScore { get; set; }
        public Nullable<int> ParentsID { get; set; }
        public Nullable<int> SpecialityID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateExam> CandidateExams { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual Speciality Speciality { get; set; }
        public bool IsEditButtonVisible { get; set; }
    }
}
