//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USSR2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateExam
    {
        public int CandidateExamID { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public int Score { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Candidate Candidate { get; set; }
    }
}
